CREATE TABLE HOSPITAL(
HOSPITAL_NAME VARCHAR(100),
LOCATION VARCHAR(100),
DEPARTMENT VARCHAR(100),
DOCTORS_COUNT INT,
PATIENT_COUNT INT,
ADMISSION_DATE DATE,
DISCHARGE_DATE DATE,
MEDICAL_EXPENSE DECIMAL(10,2)
);

--INSERT DATA INTO TABLE 
COPY
HOSPITAL(HOSPITAL_NAME, LOCATION, DEPARTMENT, DOCTORS_COUNT, PATIENT_COUNT, ADMISSION_DATE, DISCHARGE_DATE, MEDICAL_EXPENSE)
FROM'D:\Hospital_Data.csv'
CSV HEADER;

SELECT * FROM HOSPITAL;

--1)Total Number of Patients 
SELECT HOSPITAL_NAME, SUM(PATIENT_COUNT) AS TOTAL_PATIENTS 
FROM HOSPITAL
GROUP BY HOSPITAL_NAME;

--2)Average Number of Doctors per Hospital 
SELECT HOSPITAL_NAME, AVG(DOCTORS_COUNT) AS AVERAGE_DOCTORS
FROM HOSPITAL
GROUP BY HOSPITAL_NAME;

--3)Top 3 Departments with the Highest Number of Patients 
SELECT DEPARTMENT, SUM (PATIENT_COUNT)AS TOTAL_PATIENT
FROM HOSPITAL
GROUP BY DEPARTMENT
ORDER BY SUM(PATIENT_COUNT) DESC LIMIT 3;

--4)Hospital with the Maximum Medical Expenses 
SELECT HOSPITAL_NAME, SUM(MEDICAL_EXPENSE) AS TOTAL_MEDICAL_EXPENSES
FROM HOSPITAL
GROUP BY HOSPITAL_NAME
ORDER BY SUM(MEDICAL_EXPENSE)DESC LIMIT 1;

--5)Daily Average Medical Expenses 
SELECT 
    


--6)Longest Hospital Stay 
SELECT  HOSPITAL_NAME, ADMISSION_DATE, DISCHARGE_DATE,(DISCHARGE_DATE - ADMISSION_DATE) AS HOSPITAL_STAYS
FROM HOSPITAL
ORDER BY HOSPITAL_STAYS DESC LIMIT 1;

--7)Total Patients Treated Per City 
SELECT LOCATION, SUM(PATIENT_COUNT)
FROM HOSPITAL
GROUP BY LOCATION;

--8)Average Length of Stay Per Department 
SELECT DEPARTMENT, AVG(DISCHARGE_DATE - ADMISSION_DATE)AS AVERAGE_LENGTH_STAY
FROM HOSPITAL
GROUP BY DEPARTMENT;

--9)Identify the Department with the Lowest Number of Patients 
SELECT DEPARTMENT, SUM(PATIENT_COUNT)
FROM HOSPITAL
GROUP BY DEPARTMENT
ORDER BY SUM(PATIENT_COUNT) ASC LIMIT 1;

--10) Monthly Medical Expenses Report
SELECT 
    EXTRACT(MONTH FROM DISCHARGE_DATE) AS MONTH,
    SUM(MEDICAL_EXPENSE) AS TOTAL_EXPENSE
FROM HOSPITAL
GROUP BY EXTRACT(MONTH FROM DISCHARGE_DATE)
ORDER BY EXTRACT(MONTH FROM DISCHARGE_DATE) ASC;




